package com.example.domain.planner

import com.example.data.remote.FirebaseAiCloudEngine
import com.example.data.remote.GeminiClient
import com.example.domain.connectors.IntegrationService
import com.example.domain.model.GoalMilestone
import com.example.domain.repository.TaskGoalRepository
import com.example.domain.tools.AgentToolDispatcher
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

data class DecomposedGoalResult(
    val goalId: Long,
    val totalMilestones: Int,
    val phasesCount: Int,
    val summary: String
)

data class PlannedMilestone(
    val phaseNumber: Int,
    val phaseTitle: String,
    val stepTitle: String,
    val stepDescription: String,
    val suggestedTool: String,
    val scheduledDate: String = ""
)

class AutonomousGoalPlanner(
    private val taskGoalRepository: TaskGoalRepository,
    private val toolDispatcher: AgentToolDispatcher,
    private val integrationService: IntegrationService,
    private val connectorRepository: com.example.domain.connectors.ConnectorRepository? = null
) {
    suspend fun decomposeAndSaveGoal(
        title: String,
        description: String = "",
        category: String = "Productivity",
        targetDate: String = ""
    ): DecomposedGoalResult = withContext(Dispatchers.IO) {
        val goalId = taskGoalRepository.insertGoalPlan(title, description, category, targetDate)

        val prompt = """
            You are an Autonomous AI Goal Planner. Decompose this objective into 3 to 4 sequential phases, each with 1 to 2 concrete execution steps.
                
            Goal: "$title"
            Details: "$description"
            Category: "$category"
                
            For each step, specify the best automated action tool:
            - "CALENDAR" (schedule focus blocks, events)
            - "DOC" (create docs, specifications, outlines)
            - "GITHUB" (open issues, code tracking)
            - "SLACK" (team broadcast, status updates)
            - "TASK" (internal action item)
            - "NONE" (general step)
                
            Return ONLY a JSON array of objects with keys:
            [
              {
                "phaseNumber": 1,
                "phaseTitle": "Phase 1: Foundation",
                "stepTitle": "Step title",
                "stepDescription": "Detailed actionable step",
                "suggestedTool": "CALENDAR|DOC|GITHUB|SLACK|TASK|NONE"
              }
            ]
        """.trimIndent()

        val rawText = FirebaseAiCloudEngine.getInstance().generateStructuredText(
            systemInstruction = "You are Lumi's Goal Planner. Always output strictly valid JSON array of milestone objects.",
            prompt = prompt,
            temperature = 0.2f
        )

        val milestones = if (rawText.isNotBlank()) {
            parseJsonMilestones(rawText)
        } else {
            generateFallbackMilestones(title, category)
        }

        taskGoalRepository.insertMilestones(goalId, milestones)
        taskGoalRepository.updateGoalMetrics(goalId)

        DecomposedGoalResult(
            goalId = goalId,
            totalMilestones = milestones.size,
            phasesCount = milestones.distinctBy { it.phaseNumber }.size,
            summary = "Goal broken down into ${milestones.size} action steps across ${milestones.distinctBy { it.phaseNumber }.size} phases."
        )
    }

    suspend fun executeMilestoneTool(milestoneId: Long, goalId: Long): String = withContext(Dispatchers.IO) {
        val milestones = taskGoalRepository.getMilestonesForGoalSync(goalId)
        val milestone = milestones.find { it.id == milestoneId } ?: return@withContext "Milestone not found."

        var executionOutput = ""
        try {
            when (milestone.suggestedTool.uppercase(Locale.ROOT)) {
                "CALENDAR" -> {
                    val (res, report) = toolDispatcher.executeTool(
                        "add_calendar_event",
                        mapOf(
                            "title" to milestone.stepTitle,
                            "startTimeOffsetHours" to 1.0,
                            "durationMinutes" to 45,
                            "category" to "Focus",
                            "description" to milestone.stepDescription
                        )
                    )
                    executionOutput = "Scheduled calendar block: ${report.description}"
                }
                "DOC" -> {
                    val (res, report) = toolDispatcher.executeTool(
                        "google_create_doc",
                        mapOf(
                            "title" to "Roadmap: ${milestone.stepTitle}",
                            "content" to "# ${milestone.stepTitle}\n\n${milestone.stepDescription}\n\nAutonomously generated by Lumi Planner on ${SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(Date())}"
                        )
                    )
                    executionOutput = "Created Google Doc: ${report.description}"
                }
                "GITHUB" -> {
                    val repo = connectorRepository?.githubUser?.value?.takeIf { it.isNotBlank() }?.let { "$it/lumi-companion" } ?: "lumi-workspace"
                    val (res, report) = toolDispatcher.executeTool(
                        "github_create_issue",
                        mapOf(
                            "repo" to repo,
                            "title" to milestone.stepTitle,
                            "body" to milestone.stepDescription
                        )
                    )
                    executionOutput = "GitHub Issue: ${report.description}"
                }
                "SLACK" -> {
                    val channel = connectorRepository?.slackChannel?.value?.takeIf { it.isNotBlank() } ?: "general"
                    val (res, report) = toolDispatcher.executeTool(
                        "slack_post_message",
                        mapOf(
                            "channel" to channel,
                            "message" to "🚀 Starting Milestone: ${milestone.stepTitle} - ${milestone.stepDescription}"
                        )
                    )
                    executionOutput = "Broadcasted to Slack: ${report.description}"
                }
                else -> {
                    taskGoalRepository.addTask(
                        title = milestone.stepTitle,
                        notes = milestone.stepDescription,
                        priority = "HIGH",
                        category = "Goals",
                        estimatedMinutes = 30
                    )
                    executionOutput = "Created Task Item in Task Manager"
                }
            }

            taskGoalRepository.updateMilestone(
                milestone.copy(
                    isCompleted = true,
                    executionOutput = executionOutput
                )
            )
            taskGoalRepository.updateGoalMetrics(goalId)

            executionOutput
        } catch (e: Exception) {
            val errorMsg = "Execution error: ${e.localizedMessage ?: "Failed"}"
            taskGoalRepository.updateMilestone(
                milestone.copy(executionOutput = errorMsg)
            )
            errorMsg
        }
    }

    suspend fun toggleMilestone(milestoneId: Long, goalId: Long, isCompleted: Boolean) = withContext(Dispatchers.IO) {
        val milestones = taskGoalRepository.getMilestonesForGoalSync(goalId)
        val milestone = milestones.find { it.id == milestoneId }
        if (milestone != null) {
            taskGoalRepository.updateMilestone(milestone.copy(isCompleted = isCompleted))
            taskGoalRepository.updateGoalMetrics(goalId)
        }
    }

    private fun parseJsonMilestones(rawJson: String): List<PlannedMilestone> {
        val list = mutableListOf<PlannedMilestone>()
        try {
            val clean = rawJson.trim().removePrefix("```json").removePrefix("```").removeSuffix("```").trim()
            val array = if (clean.startsWith("[")) {
                JSONArray(clean)
            } else if (clean.startsWith("{")) {
                val obj = JSONObject(clean)
                obj.optJSONArray("milestones") ?: JSONArray()
            } else {
                JSONArray()
            }

            for (i in 0 until array.length()) {
                val item = array.getJSONObject(i)
                val phaseNum = item.optInt("phaseNumber", (i / 2) + 1)
                val phaseTitle = item.optString("phaseTitle", "Phase $phaseNum")
                val stepTitle = item.optString("stepTitle", "Milestone ${i + 1}")
                val stepDesc = item.optString("stepDescription", "Action step")
                val tool = when (item.optString("suggestedTool", "TASK").uppercase(Locale.ROOT)) {
                    "CALENDAR", "DOC", "GITHUB", "SLACK", "TASK" -> item.optString("suggestedTool", "TASK").uppercase(Locale.ROOT)
                    else -> "TASK"
                }
                list.add(PlannedMilestone(phaseNum, phaseTitle, stepTitle, stepDesc, tool))
            }
        } catch (_: Exception) {}

        return if (list.isNotEmpty()) list else generateFallbackMilestones("Goal", "Productivity")
    }

    private fun generateFallbackMilestones(title: String, category: String): List<PlannedMilestone> {
        return listOf(
            PlannedMilestone(
                phaseNumber = 1,
                phaseTitle = "Phase 1: Discovery & Architecture",
                stepTitle = "Draft Project Scope Document",
                stepDescription = "Synthesize requirements, milestones, and success criteria for '$title'.",
                suggestedTool = "DOC"
            ),
            PlannedMilestone(
                phaseNumber = 2,
                phaseTitle = "Phase 2: Execution Sprint",
                stepTitle = "Deep Focus Implementation Block",
                stepDescription = "Schedule dedicated 45-minute focus session to build core components.",
                suggestedTool = "CALENDAR"
            ),
            PlannedMilestone(
                phaseNumber = 3,
                phaseTitle = "Phase 3: Integration & Testing",
                stepTitle = "Open Tracking Issue on GitHub",
                stepDescription = "File tracking issue for QA, edge cases, and continuous integration.",
                suggestedTool = "GITHUB"
            ),
            PlannedMilestone(
                phaseNumber = 4,
                phaseTitle = "Phase 4: Launch & Retrospective",
                stepTitle = "Broadcast Objective Success to Team",
                stepDescription = "Send completion message and summary update to team channel.",
                suggestedTool = "SLACK"
            )
        )
    }
}
