package com.example.domain.apps

import org.json.JSONArray
import org.json.JSONObject

enum class WidgetType {
    ACTION_CARD,
    CHECKLIST_APP,
    PROGRESS_TRACKER,
    METRIC_COUNTER,
    INFO_BANNER
}

data class DynamicWidgetSpec(
    val id: String,
    val title: String,
    val description: String,
    val type: WidgetType,
    val items: List<String> = emptyList(),
    val primaryActionLabel: String = "Execute",
    val secondaryActionLabel: String = "Dismiss"
)

/**
 * Local App Builder Engine allowing Lumi agents to dynamically construct mini-apps
 * and interactive dynamic UI widgets on demand for the user.
 */
object LocalAppBuilderEngine {

    fun parseWidgetSpec(jsonStr: String): DynamicWidgetSpec? {
        return try {
            val clean = jsonStr.trim().removePrefix("```json").removePrefix("```").removeSuffix("```").trim()
            val json = JSONObject(clean)

            val typeStr = json.optString("type", "ACTION_CARD").uppercase(java.util.Locale.ROOT)
            val widgetType = try { WidgetType.valueOf(typeStr) } catch (_: Exception) { WidgetType.ACTION_CARD }

            val itemsArr = json.optJSONArray("items") ?: JSONArray()
            val itemsList = mutableListOf<String>()
            for (i in 0 until itemsArr.length()) itemsList.add(itemsArr.getString(i))

            DynamicWidgetSpec(
                id = json.optString("id", "app_${System.currentTimeMillis()}"),
                title = json.optString("title", "Custom Local App 🚀"),
                description = json.optString("description", "Interactive dynamic app generated by Lumi"),
                type = widgetType,
                items = itemsList,
                primaryActionLabel = json.optString("primaryActionLabel", "Execute Action"),
                secondaryActionLabel = json.optString("secondaryActionLabel", "Dismiss")
            )
        } catch (e: Exception) {
            null
        }
    }

    fun buildDefaultTrackerApp(title: String, steps: List<String>): DynamicWidgetSpec {
        return DynamicWidgetSpec(
            id = "app_tracker_${System.currentTimeMillis().toString().takeLast(6)}",
            title = title,
            description = "Custom Interactive Tracker App",
            type = WidgetType.CHECKLIST_APP,
            items = steps,
            primaryActionLabel = "Complete All",
            secondaryActionLabel = "Save App"
        )
    }
}
