package com.example

import android.app.Application
import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.os.Build

import com.example.core.di.appModule
import com.google.firebase.FirebaseApp
import com.google.firebase.FirebaseOptions
import android.util.Log
import org.koin.android.ext.koin.androidContext
import org.koin.android.ext.koin.androidLogger
import org.koin.core.context.startKoin

class LumiApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        
        // Set App Check debug token as early as possible
        setupAppCheckDebugToken()
        
        initializeFirebase()

        if (org.koin.core.context.GlobalContext.getOrNull() == null) {
            startKoin {
                androidLogger()
                androidContext(this@LumiApplication)
                modules(appModule)
            }
        }
        
        createNotificationChannels()
    }

    private fun initializeFirebase() {
        try {
            if (FirebaseApp.getApps(this).isEmpty()) {
                val app = FirebaseApp.initializeApp(this)
                if (app == null) {
                    val options = FirebaseOptions.Builder()
                        .setApplicationId("1:663377968514:android:bac0ab54e860f4ed40639b")
                        .setApiKey("AIzaSyBwusrDv4IY6WvoP7Nqb5FKn3DcdmxYiXk")
                        .setProjectId("studio-8325749739-eefac")
                        .setDatabaseUrl("https://studio-8325749739-eefac-default-rtdb.asia-southeast1.firebasedatabase.app")
                        .setStorageBucket("studio-8325749739-eefac.firebasestorage.app")
                        .setGcmSenderId("663377968514")
                        .build()
                    FirebaseApp.initializeApp(this, options)
                    Log.i("LumiApp", "Firebase initialized with explicit fallback options")
                } else {
                    Log.i("LumiApp", "Firebase initialized automatically from google-services")
                }
            }
            // Initialize Firebase App Check with Play Integrity provider
            com.example.data.firebase.LumiAppCheckManager.getInstance().initialize()
            
            setupFcmSkipping()
        } catch (e: Exception) {
            Log.e("LumiApp", "Error during Firebase initialization", e)
        }
    }

    private fun setupAppCheckDebugToken() {
        if (BuildConfig.DEBUG) {
            try {
                // Read via reflection to avoid compilation errors if not generated by secrets plugin
                val field = BuildConfig::class.java.getDeclaredField("FIREBASE_APPCHECK_DEBUG_TOKEN")
                val debugToken = field.get(null) as? String
                if (!debugToken.isNullOrEmpty() && debugToken != "none") {
                    Log.i("LumiApp", "Setting Firebase App Check debug token from BuildConfig")
                    System.setProperty("debug.firebase.appcheck.token", debugToken)
                } else {
                    Log.w("LumiApp", "App Check debug token is empty or not provided.")
                }
            } catch (e: NoSuchFieldException) {
                Log.w("LumiApp", "FIREBASE_APPCHECK_DEBUG_TOKEN not found in BuildConfig. Provide it in .env if needed.")
            } catch (e: Exception) {
                Log.e("LumiApp", "Failed to set App Check debug token", e)
            }
        }
    }

    private fun setupFcmSkipping() {
        val isEmulator = (android.os.Build.BRAND.startsWith("generic") && android.os.Build.DEVICE.startsWith("generic"))
                || android.os.Build.FINGERPRINT.startsWith("generic")
                || android.os.Build.FINGERPRINT.startsWith("unknown")
                || android.os.Build.HARDWARE.contains("goldfish")
                || android.os.Build.HARDWARE.contains("ranchu")
                || android.os.Build.HARDWARE.contains("cutf_cvm")
                || android.os.Build.MODEL.contains("google_sdk")
                || android.os.Build.MODEL.contains("Emulator")
                || android.os.Build.MODEL.contains("Android SDK built for x86")
                || android.os.Build.MANUFACTURER.contains("Genymotion")
                || android.os.Build.PRODUCT.contains("sdk_google")
                || android.os.Build.PRODUCT.contains("google_sdk")
                || android.os.Build.PRODUCT.contains("sdk")
                || android.os.Build.PRODUCT.contains("sdk_x86")
                || android.os.Build.PRODUCT.contains("vbox86p")
                || android.os.Build.PRODUCT.contains("emulator")
                || android.os.Build.PRODUCT.contains("simulator")

        if (com.example.BuildConfig.DEBUG && isEmulator) {
            Log.d("LumiApp", "Running on emulator, skipping FCM programatic interactions.")
        }
    }

    private fun createNotificationChannels() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                "lumi_companion_service",
                "Lumi Companion Service",
                NotificationManager.IMPORTANCE_LOW
            ).apply {
                description = "Shows floating Lumi pet companion overlay status"
            }

            val reminderChannel = NotificationChannel(
                "lumi_reminders",
                "Lumi Daily Check-Ins",
                NotificationManager.IMPORTANCE_DEFAULT
            ).apply {
                description = "Daily wellness, mindfulness and schedule reminders from Lumi"
            }

            val fcmChannel = NotificationChannel(
                com.example.framework.LumiFirebaseMessagingService.CHANNEL_PROACTIVE_ALERTS,
                "Lumi Proactive Companion Alerts",
                NotificationManager.IMPORTANCE_HIGH
            ).apply {
                description = "Proactive check-ins, mindful nudges, and real-time alerts from your companion Lumi"
                enableVibration(true)
            }

            val manager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
            manager.createNotificationChannel(channel)
            manager.createNotificationChannel(reminderChannel)
            manager.createNotificationChannel(fcmChannel)
        }
        
        // Subscribe to companion notification topics
        val isEmulator = (android.os.Build.BRAND.startsWith("generic") && android.os.Build.DEVICE.startsWith("generic"))
                || android.os.Build.FINGERPRINT.startsWith("generic")
                || android.os.Build.FINGERPRINT.startsWith("unknown")
                || android.os.Build.HARDWARE.contains("goldfish")
                || android.os.Build.HARDWARE.contains("ranchu")
                || android.os.Build.HARDWARE.contains("cutf_cvm")
                || android.os.Build.MODEL.contains("google_sdk")
                || android.os.Build.MODEL.contains("Emulator")
                || android.os.Build.MODEL.contains("Android SDK built for x86")
                || android.os.Build.PRODUCT.contains("sdk")
                || android.os.Build.PRODUCT.contains("emulator")
                || android.os.Build.PRODUCT.contains("simulator")
                
        if (!isEmulator) {
            com.example.framework.LumiFirebaseMessagingService.subscribeToCompanionTopics()
        }
    }
}
